import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/app/**/*.{ts,tsx}",
    "./src/components/**/*.{ts,tsx}",
    "./src/lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface": "#e5e2e1",
        "on-primary-fixed": "#002020",
        "surface-variant": "#353534",
        "surface-bright": "#3a3939",
        surface: "#131313",
        "inverse-on-surface": "#313030",
        error: "#ffb4ab",
        secondary: "#c6c6c6",
        "surface-dim": "#131313",
        "outline-variant": "#3a4a49",
        "primary-container": "#00fbfb",
        background: "#050505",
        "secondary-fixed": "#e2e2e2",
        "on-error": "#690005",
        "tertiary-fixed": "#e5e2e1",
        outline: "#839493",
        "primary-fixed": "#00fbfb",
        "on-primary-container": "#007070",
        "secondary-container": "#454747",
        "on-secondary": "#2f3131",
        tertiary: "#ffffff",
        "surface-container-low": "#1c1b1b",
        "inverse-primary": "#006a6a",
        "surface-tint": "#00dddd",
        "tertiary-container": "#e5e2e1",
        "surface-container": "#201f1f",
        "on-tertiary-container": "#656464",
        "on-tertiary": "#313030",
        "on-primary": "#003737",
        "inverse-surface": "#e5e2e1",
        "on-secondary-container": "#b5b5b5",
        "primary-fixed-dim": "#00dddd",
        primary: "#ffffff",
        "tertiary-fixed-dim": "#c8c6c5",
        "on-primary-fixed-variant": "#004f4f",
        "surface-container-lowest": "#0e0e0e",
        "on-surface-variant": "#b9cac9",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#454747",
        "on-background": "#e5e2e1",
        "error-container": "#93000a",
        "surface-container-highest": "#353534",
        "surface-container-high": "#2a2a2a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-sm": "8px",
        "stack-lg": "32px",
        "stack-xl": "64px",
        "stack-md": "16px",
        "margin-desktop": "40px",
        "margin-mobile": "20px",
        gutter: "16px",
        base: "8px",
      },
      fontFamily: {
        "label-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-lg-mobile": ["var(--font-hanken)", "Hanken Grotesk", "sans-serif"],
        "display-md": ["var(--font-hanken)", "Hanken Grotesk", "sans-serif"],
        "display-lg": ["var(--font-hanken)", "Hanken Grotesk", "sans-serif"],
        "headline-lg": ["var(--font-hanken)", "Hanken Grotesk", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "1.1", letterSpacing: "0.03em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-lg-mobile": ["20px", { lineHeight: "1.3", fontWeight: "600" }],
        "display-md": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
      maxWidth: {
        "7xl": "80rem",
      },
    },
  },
  plugins: [],
};

export default config;
